# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'TRTC-API-Example-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TRTC-API-Example-OC
  pod 'TXLiteAVSDK_TRTC'
end

target 'TXReplayKit_Screen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TXReplayKit_Screen
  pod 'TXLiteAVSDK_TRTC/ReplayKitExt'
end
